#!/bin/bash

#skript backupi tegemiseks

echo "=========[BACKUP]========="
echo -n "Sisesta kataloogi nimi:"
read katalooginimi

date=$(date +"%d.%m.%Y")
baasnimi="$(basename -- $katalooginimi)" #võtame katalooginimest ainult baasnime
asukoht="/home/user/skriptimine/praks4a/backup/$baasnimi.backup.$date.tar.gz" #backupi asukoht
tar -zcvf $asukoht $katalooginimi #loome kokkupakitud faili

echo "Kataloogi $katalooginimi backup'i nimi on $baasnimi.backup.$date.tar.gz ja ta asub $asukoht"
echo "=========================="
#skripti lõpp
