#!/bin/bash

#skript, mis väljastab, kas arv on paaris või mitte.

if [ $# != 1 ]
then
 echo "$(tput setaf 7)$(tput setab 1)[VIGA]:$(tput setab 7)$(tput setaf 0) Käivita see skript koos arvuga, mille paarsust soovid kontrollida."
 echo -n "$(tput setaf 0)$(tput setab 6)[NÄIDE]:$(tput setab 7)$(tput setaf 0) ./paarsus 3"
 echo "$(tput sgr0)" #värvid terminalis normaalseks tagasi
else
 tarv=$1
 jaak=$(($tarv%2))
 if [ $jaak == 0 ] 
 then
  echo "$tarv on paarisarv."
 else
  echo "$tarv on paaritu arv."
 fi
fi
