#!/bin/bash

#skript, mis väljastab, kas arv on paaris või mitte.

if [ $# != 1 ]
then
 echo -e -n "$(tput setaf 7)$(tput setab 1)[VIGA]:$(tput setab 7)$(tput setaf 0) Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: ./paarsus 3"
 echo -e "$(tput sgr0)" #värvid tagasi normaalseks
else
 tarv=$1
 jaak=$(($tarv%2))
 if [ $jaak == 0 ] 
 then
  echo "$tarv on paarisarv."
 else
  echo "$tarv on paaritu arv."
 fi
fi
