#!/bin/bash
# Minu esimene skript
# tervitab kasutajat

echo -n "Tere, " #väljastame teksti Tere ilma reavahetuseta (-n)
echo -n "User" #väljastame teksti User ilma reavahetuseta (-n)
echo "!" #väljastame hüüumärgi 

# skripti lõpp
